import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router';
import AppLayout from '@/layouts/AppLayout.vue';
import { menus } from './menu';
const Dashboard = () => import('@/views/dashboard/DashboardView.vue');
const pageMap: Record<string, () => Promise<unknown>> = {
 '/assets/catalog':()=>import('@/views/assets/AssetCatalog.vue'), '/assets/files':()=>import('@/views/assets/FileManager.vue'), '/assets/metadata':()=>import('@/views/assets/MetadataManager.vue'), '/assets/versions':()=>import('@/views/assets/VersionManager.vue'), '/assets/lineage':()=>import('@/views/assets/LineageView.vue'),
 '/knowledge/compile-tasks':()=>import('@/views/knowledge/CompileTasks.vue'), '/knowledge/markdown':()=>import('@/views/knowledge/MarkdownFiles.vue'), '/knowledge/chunks':()=>import('@/views/knowledge/ChunksManager.vue'), '/knowledge/policies':()=>import('@/views/knowledge/PolicyEntities.vue'), '/knowledge/policy-graph':()=>import('@/views/knowledge/PolicyGraph.vue'), '/knowledge/conflicts':()=>import('@/views/knowledge/KnowledgeConflicts.vue'), '/knowledge/missing':()=>import('@/views/knowledge/MissingKnowledge.vue'),
 '/rules/list':()=>import('@/views/rules/RulesList.vue'), '/rules/test':()=>import('@/views/rules/RuleTest.vue'), '/rules/conflicts':()=>import('@/views/knowledge/KnowledgeConflicts.vue'), '/skills/list':()=>import('@/views/skills/SkillsList.vue'), '/skills/expert-workbench':()=>import('@/views/skills/ExpertWorkbench.vue'), '/skills/orchestration':()=>import('@/views/skills/SkillOrchestration.vue'), '/skills/test':()=>import('@/views/rules/RuleTest.vue'),
 '/tools/list':()=>import('@/views/tools/ToolsList.vue'), '/tools/register':()=>import('@/views/tools/ToolRegister.vue'), '/tools/schema':()=>import('@/views/tools/SchemaConfig.vue'), '/tools/test':()=>import('@/views/tools/ToolTest.vue'), '/tools/permissions':()=>import('@/views/tools/ToolPermissions.vue'), '/tools/logs':()=>import('@/views/common/GenericPage.vue'), '/tools/status':()=>import('@/views/common/GenericPage.vue'),
 '/evaluation/asset-health':()=>import('@/views/evaluation/AssetHealth.vue'), '/evaluation/knowledge':()=>import('@/views/common/GenericPage.vue'), '/evaluation/answers':()=>import('@/views/evaluation/AnswerQuality.vue'), '/evaluation/tools':()=>import('@/views/common/GenericPage.vue'), '/evaluation/skills':()=>import('@/views/common/GenericPage.vue'), '/evaluation/cases':()=>import('@/views/evaluation/TestCases.vue'), '/evaluation/regression':()=>import('@/views/common/GenericPage.vue'), '/learning/conversations':()=>import('@/views/learning/Conversations.vue'), '/learning/missing-knowledge':()=>import('@/views/knowledge/MissingKnowledge.vue'), '/learning/tasks':()=>import('@/views/common/GenericPage.vue'),
 '/terminals/list':()=>import('@/views/terminals/TerminalList.vue'), '/terminals/window-assistant':()=>import('@/views/terminals/TerminalConfig.vue'), '/terminals/digital-human':()=>import('@/views/terminals/TerminalConfig.vue'), '/terminals/robot':()=>import('@/views/terminals/TerminalConfig.vue'), '/terminals/self-service':()=>import('@/views/terminals/TerminalConfig.vue'), '/terminals/permissions':()=>import('@/views/terminals/TerminalConfig.vue'), '/terminals/rate-limit':()=>import('@/views/terminals/TerminalConfig.vue'),
 '/review/my-tasks':()=>import('@/views/review/ReviewTasks.vue'), '/review/task-pool':()=>import('@/views/review/ReviewTasks.vue'), '/review/publish-records':()=>import('@/views/common/GenericPage.vue'), '/review/rejected':()=>import('@/views/common/GenericPage.vue'), '/review/rollback':()=>import('@/views/assets/VersionManager.vue'), '/review/policies':()=>import('@/views/common/GenericPage.vue'),
 '/audit/traces':()=>import('@/views/audit/TracesView.vue'), '/audit/knowledge-logs':()=>import('@/views/common/GenericPage.vue'), '/audit/tool-logs':()=>import('@/views/common/GenericPage.vue'), '/audit/skill-logs':()=>import('@/views/common/GenericPage.vue'), '/audit/permission-logs':()=>import('@/views/common/GenericPage.vue'), '/audit/operation-logs':()=>import('@/views/common/GenericPage.vue'), '/audit/alerts':()=>import('@/views/common/GenericPage.vue'),
 '/system/users':()=>import('@/views/system/SystemTables.vue'), '/system/roles':()=>import('@/views/system/SystemTables.vue'), '/system/orgs':()=>import('@/views/system/SystemTables.vue'), '/system/permissions':()=>import('@/views/system/SystemTables.vue'), '/system/dictionaries':()=>import('@/views/system/SystemTables.vue'), '/system/models':()=>import('@/views/system/SystemTables.vue'), '/system/vector-config':()=>import('@/views/system/SystemTables.vue'), '/system/settings':()=>import('@/views/system/SystemTables.vue')
};
const children: RouteRecordRaw[] = [{ path:'/dashboard', component: Dashboard, meta:{title:'工作台首页'} }];
menus.flatMap(m=>m.children||[]).forEach(i=>children.push({path:i.path!, component: pageMap[i.path!] as any, meta:{title:i.title}}));
export default createRouter({ history:createWebHistory(), routes:[{ path:'/', component:AppLayout, redirect:'/dashboard', children }, { path:'/:pathMatch(.*)*', redirect:'/dashboard' }] });
