import type { MenuItem } from '@/types';
export const menus: MenuItem[] = [
 {title:'工作台首页',path:'/dashboard',icon:'DataBoard'},
 {title:'数据资产目录',icon:'Files',children:[['资产总目录','/assets/catalog'],['原始文件管理','/assets/files'],['元数据管理','/assets/metadata'],['资产版本管理','/assets/versions'],['资产血缘关系','/assets/lineage']].map(([title,path])=>({title,path}))},
 {title:'知识工程中心',icon:'Reading',children:[['智能编译任务','/knowledge/compile-tasks'],['Markdown 编译文件','/knowledge/markdown'],['知识切片管理','/knowledge/chunks'],['政策实体管理','/knowledge/policies'],['政策关系图谱','/knowledge/policy-graph'],['知识冲突检测','/knowledge/conflicts'],['知识缺失检测','/knowledge/missing']].map(([title,path])=>({title,path}))},
 {title:'规则与技能中心',icon:'Connection',children:[['规则库','/rules/list'],['规则测试','/rules/test'],['规则冲突检测','/rules/conflicts'],['技能库','/skills/list'],['业务专家工作台','/skills/expert-workbench'],['技能编排','/skills/orchestration'],['技能测试','/skills/test']].map(([title,path])=>({title,path}))},
 {title:'工具中心',icon:'Tools',children:[['工具库','/tools/list'],['工具注册','/tools/register'],['Schema 配置','/tools/schema'],['工具测试','/tools/test'],['工具权限配置','/tools/permissions'],['工具调用日志','/tools/logs'],['工具运行状态','/tools/status']].map(([title,path])=>({title,path}))},
 {title:'评估与学习中心',icon:'TrendCharts',children:[['数据资产健康度','/evaluation/asset-health'],['知识质量评估','/evaluation/knowledge'],['回答质量评估','/evaluation/answers'],['工具可用性评估','/evaluation/tools'],['技能效果评估','/evaluation/skills'],['测试用例库','/evaluation/cases'],['回归测试任务','/evaluation/regression'],['会话记录','/learning/conversations'],['知识缺失池','/learning/missing-knowledge'],['学习整改任务','/learning/tasks']].map(([title,path])=>({title,path}))},
 {title:'终端能力管理',icon:'Monitor',children:[['终端列表','/terminals/list'],['窗口助手配置','/terminals/window-assistant'],['数字人配置','/terminals/digital-human'],['机器人配置','/terminals/robot'],['自助终端配置','/terminals/self-service'],['终端能力授权','/terminals/permissions'],['终端限流策略','/terminals/rate-limit']].map(([title,path])=>({title,path}))},
 {title:'审核发布中心',icon:'Checked',children:[['待我审核','/review/my-tasks'],['审核任务池','/review/task-pool'],['发布记录','/review/publish-records'],['驳回记录','/review/rejected'],['版本回滚','/review/rollback'],['发布策略配置','/review/policies']].map(([title,path])=>({title,path}))},
 {title:'运行监控与审计',icon:'Histogram',children:[['智脑调用 Trace','/audit/traces'],['知识召回日志','/audit/knowledge-logs'],['工具调用日志','/audit/tool-logs'],['技能命中日志','/audit/skill-logs'],['权限拦截日志','/audit/permission-logs'],['操作审计日志','/audit/operation-logs'],['异常告警','/audit/alerts']].map(([title,path])=>({title,path}))},
 {title:'系统管理',icon:'Setting',children:[['用户管理','/system/users'],['角色管理','/system/roles'],['组织管理','/system/orgs'],['权限策略','/system/permissions'],['字典配置','/system/dictionaries'],['模型配置','/system/models'],['向量库配置','/system/vector-config'],['系统参数','/system/settings']].map(([title,path])=>({title,path}))}
];
export function titleByPath(path:string){ for(const m of menus){ if(m.path===path) return [m.title]; const c=m.children?.find(i=>i.path===path); if(c) return [m.title,c.title]; } return ['工作台首页']; }
