import { domainService } from '@/services/domainService';
import { mockResolve } from './http';

export const api = {
  dashboard: () => mockResolve(domainService.getDashboard()),
  assets: () => mockResolve(domainService.db.assets),
  files: () => mockResolve(domainService.db.files),
  metadata: () => mockResolve(domainService.db.metadata),
  versions: () => mockResolve(domainService.db.versions),
  compileTasks: () => mockResolve(domainService.db.compileTasks),
  markdownDocs: () => mockResolve(domainService.db.markdownDocs),
  chunks: () => mockResolve(domainService.db.chunks),
  policies: () => mockResolve(domainService.db.policies),
  conflicts: () => mockResolve(domainService.db.conflicts),
  missing: () => mockResolve(domainService.db.missingKnowledge),
  rules: () => mockResolve(domainService.db.rules),
  skills: () => mockResolve(domainService.db.skills),
  tools: () => mockResolve(domainService.db.tools),
  health: () => mockResolve(domainService.db.healthScores),
  conversations: () => mockResolve(domainService.db.conversations),
  reviews: () => mockResolve(domainService.db.reviewTasks),
  traces: () => mockResolve(domainService.db.traces),
  terminals: () => mockResolve(domainService.db.terminals),
  assetDetail: (assetId: string) => mockResolve(domainService.getAssetDetail(assetId)),
  skillDetail: (skillId: string) => mockResolve(domainService.getSkillDetail(skillId)),
  traceDetail: (traceId: string) => mockResolve(domainService.getTraceDetail(traceId)),
  submitReview: (objectType: any, objectId: string, title?: string) => mockResolve(domainService.submitReview(objectType, objectId, title)),
  review: (reviewId: string, status: any, opinion: string) => mockResolve(domainService.review(reviewId, status, opinion)),
  publish: (objectType: any, objectId: string) => mockResolve(domainService.publish(objectType, objectId)),
  rollback: (versionId: string) => mockResolve(domainService.rollback(versionId)),
  startCompile: (fileId: string) => mockResolve(domainService.startCompile(fileId)),
  simulateTool: (payload: any) => mockResolve(domainService.simulateTool(payload.toolId, payload.params)),
  generateSkill: (prompt = '') => mockResolve(domainService.generateSkillDraft(prompt)),
  saveSkillDraft: (draft: any) => mockResolve(domainService.saveSkillDraft(draft)),
  simulateBrainCall: (question: string, terminalId: string) => mockResolve(domainService.simulateBrainCall(question, terminalId)),
};
